--CRIAÇÂO DATA-BASE

CREATE DATABASE "agenda-eventos"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Portuguese_Brazil.1252'
    LC_CTYPE = 'Portuguese_Brazil.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

-- CRIAÇÃO DAS TABLEAS
-- Tabela Usuários
CREATE TABLE USUARIOS (
  ID INT PRIMARY KEY,
  NOME VARCHAR(50),
  EMAIL VARCHAR(100) UNIQUE,
  TELEFONE VARCHAR(14) UNIQUE,
  CPF VARCHAR(11) UNIQUE
);

-- Tabela Endereco
CREATE TABLE ENDERECO (
  ID INT PRIMARY KEY,
  ESTADO VARCHAR(20),
  CIDADE VARCHAR(50),
  RUA VARCHAR(150),
  NUMERO VARCHAR(5),
  PONTO_DE_REFERENCIA VARCHAR(255)
);

-- Tabela Bandas
CREATE TABLE BANDAS (
  ID INT PRIMARY KEY,
  NOME VARCHAR(50),
  EMAIL VARCHAR(100) UNIQUE,
  DESCRICAO VARCHAR(255),
  TELEFONE VARCHAR(14) UNIQUE,
  CPF_CNPJ VARCHAR(14) UNIQUE
);

-- Tabela Agenda
CREATE TABLE AGENDA (
  ID INT PRIMARY KEY,
  BANDA_ID INT,
  DATA DATE,
  HORARIO_INICIO TIME,
  HORARIO_TERMINO TIME
);

-- Tabela Eventos
CREATE TABLE EVENTOS (
  ID INT PRIMARY KEY,
  BANDA_ID INT,
  DATA DATE,
  HORARIO_INICIO TIME,
  HORARIO_TERMINO TIME
);

-- ADICIOANNDO RELACIONAMENTO

-- Adicionar coluna ENDERECO_ID na tabela Usuarios
ALTER TABLE USUARIOS
ADD COLUMN ENDERECO_ID INT,
ADD FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO(ID);

-- Adicionar coluna ENDERECO_ID na tabela Eventos
ALTER TABLE EVENTOS
ADD COLUMN ENDERECO_ID INT,
ADD FOREIGN KEY (ENDERECO_ID) REFERENCES ENDERECO(ID);